LsManagement/LsManagement/urls.py
from django.contrib import admin  
from django.conf.urls import url, include
from employee import views  
urlpatterns = [  
    url('admin/', admin.site.urls), 
    url('music/', include('music.urls')), 
    url('emp', views.emp),  
    url('show',views.show),  
    url('edit/<int:id>', views.edit),  
    url('update/<int:id>', views.update),  
    url('delete/<int:id>', views.destroy),  
]

LsManagement/music/urls.py
from django.conf.urls import url, include
from . import views
urlpatterns = [
    url(r'^$',views.index),
    url(r'^add/$',views.addAlbum),
    url(r'^signup/$',views.signUp),
    url(r'^registerUsers/$',views.registerUsers),
    url(r'^signIn/$',views.signIn),
    url(r'^addMusicAlbum/$',views.addMusicAlbum),
    # url('emp', views.emp),
    url(r'^(?P<album_id>[0-9]+)/$', views.detail),
    url(r'^learn/$', views.showForm),
    url(r'^countss/$', views.showCount, name='count'),
    url(r'^homepage/$', views.showForm, name='home')
]

LsManagement/employee/models.py
from django.db import models  
class Employee(models.Model):  
    eid = models.CharField(max_length=20)  
    ename = models.CharField(max_length=100)  
    eemail = models.EmailField()  
    econtact = models.CharField(max_length=15)
    created_at = models.DateTimeField(auto_now_add=True)
    class Meta:  
        db_table = "employee"


class EmployeeDetail(models.Model): 
    eid = models.CharField(max_length=20)  
    eDob = models.CharField(max_length=100)  
    eGender = models.EmailField()
    eAddress = models.CharField(max_length=254)
    eJoiningDate = models.DateTimeField(auto_now_add=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
      
    class Meta:  
        db_table = "employeeDetail"

LsManagement/music/models.py
from django.db import models

# Create your models here.
class Album(models.Model):
	artist = models.CharField(max_length=250)
	album_title = models.CharField(max_length=500)
	genre = models.CharField(max_length=100)
	album_logo = models.CharField(max_length=1000)

class User(models.Model):
	userName = models.CharField(max_length=100)
	mobile = models.CharField(max_length=50)
	email = models.CharField(max_length=100)
	city = models.CharField(max_length=50)
	state = models.CharField(max_length=50)
	address = models.CharField(max_length=500)
	password = models.CharField(max_length=200)
	status = models.CharField(max_length=1000)
	created_at = models.DateTimeField(auto_now_add=True)


class SongTypes(models.Model):
	song_type = models.CharField(max_length=100)
	created_at = models.DateTimeField(auto_now_add=True)
	is_favorite = models.BooleanField(default=False)
	class Meta:
		db_table = "song_types"

class Song(models.Model):
	album = models.ForeignKey(Album, on_delete = models.CASCADE)
	typeId = models.ForeignKey(SongTypes, on_delete = models.CASCADE)
	file_type = models.CharField(max_length=10)
	song_title = models.CharField(max_length=250)

LsManagement/employee/forms.py
from django import forms  
from employee.models import Employee  
class EmployeeForm(forms.ModelForm):  
    class Meta:  
        model = Employee  
        fields = "__all__"  

LsManagement/employee/views.py
from django.shortcuts import render, redirect
from employee.forms import EmployeeForm
from employee.models import Employee
# Create your views here.  
def emp(request):
    if request.method == "POST":
        form = EmployeeForm(request.POST)
        if form.is_valid():
            try:  
                form.save()  
                return redirect('/show')  
            except:  
                pass  
    else:
        form = EmployeeForm()
    return render(request,'index.html',{'form':form})  
def show(request):
    employees = Employee.objects.all()  
    return render(request,"show.html",{'employees':employees})

def edit(request, id):  
    employee = Employee.objects.get(id=id)  
    return render(request,'edit.html', {'employee':employee})

def update(request, id):  
    employee = Employee.objects.get(id=id)  
    form = EmployeeForm(request.POST, instance = employee)  
    if form.is_valid():  
        form.save()  
        return redirect("/show")  
    return render(request, 'edit.html', {'employee': employee})
     
def destroy(request, id):  
    employee = Employee.objects.get(id=id)  
    employee.delete()  
    return redirect("/show")

def destroy(request):  
    employee = Employee.objects.get(id=id)  
    employee.delete()  
    return redirect("/show")

LsManagement/music/views.py
from django.shortcuts import render
from django.http import HttpResponse, Http404
from django.template import loader
from .models import Album ,SongTypes, User
import cgi
import operator

# Create your views here.
def index(request):
	all_albums = Album.objects.all()
	#all_albums = Album.objects.raw('select * from music_album')
	#cursor.execute("select * from ls_hero_testride_enquiry")
	context = {
		'all_albums' : all_albums,
	}
	return render(request,'music/index.html',context)

def addAlbum(request):
	context = {
		'text' : 'Add Music Album',
	}
	return render(request,'music/addAlbum.html',context)

def signUp(request):
	context = {
		'text' : 'Add Music Album',
	}
	return render(request,'login/index.html',context)

def signIn(request):
	context = {
		'text' : 'Add Music Album',
	}
	return render(request,'login/signIn.html',context)



def registerUsers(request):

	# form = cgi.FieldStorage()
	# artist =  form.getvalue('artist')
	user = User()
	formValue = request.POST
	user.userName = formValue.get('userName').strip()
	user.mobile = formValue.get('mobile').strip()
	user.email = formValue.get('email').strip()
	user.city = formValue.get('city').strip()
	user.state = formValue.get('state').strip()
	user.address = formValue.get('address').strip()
	user.password = formValue.get('password').strip()
	if user.userName and user.mobile and user.email and user.city:
		user.save()
	else:
		return HttpResponse("Please fill all the fields")
	
	#return HttpResponse("Data saved successfully.")
	context = {
		'text' : 'Data saved successfully.',
	}
	return render(request,'login/signIn.html',context)
	#return render(request,'music/addAlbum.html',context)


def addMusicAlbum(request):

	# form = cgi.FieldStorage()
	# artist =  form.getvalue('artist')
	album = Album()
	formValue = request.POST

	album.artist = formValue.get('artist').strip()
	album.album_title = formValue.get('title').strip()
	album.genre = formValue.get('genre').strip()
	album.album_logo = formValue.get('logo').strip()
	if album.artist and album.album_title and album.genre and album.album_logo:
		album.save()
	else:
		return HttpResponse("Please fill all the fields")
	
	return HttpResponse("Data saved successfully.")
	#return render(request,'music/addAlbum.html',context)


def detail(request,album_id):
	try:
		album = Album.objects.get(pk=album_id)
		all_types = SongTypes.objects.all()
		#return HttpResponse(all_types)
	except:
		raise Http404("Album does not exist")
	return render(request,'music/detail.html',{'album': album, 'all_types' : all_types})


def showForm(request):
	try:
		data="hello world"
		name="Prakash Sahu"
		return render(request,'music/showForm.html',{'text':data, 'name':name})
	except:
		raise Http404("page does not exist")


def showCount(request):
	try:
		textval = request.GET['textarea']
		wordList = textval.split();
		length = len(wordList)
		print(wordList)
		worddict = {}
		for word in wordList:
			if word in worddict:
				worddict[word] += 1
			else:
				worddict[word] = 1
		sorted_list = sorted(worddict.items(), key = operator.itemgetter(1), reverse=True)
		#reverse is used to make asc or desc order
		#sorted function is used to sort the dictionary
		return render(request,'music/showDetail.html',{'text':textval, 'worddict':sorted_list, 'length':length})
		
	except:
		raise Http404("Album does not exist")

LsManagement/employee/templates/edit.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Index</title>  
    {% load staticfiles %}  
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/> 
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script> 
</head>  
<body>  
<form method="POST" class="post-form" action="/update/{{employee.id}}">  
        {% csrf_token %}  
    <div class="container">  
<br>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <h3>Update Details</h3>  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Employee Id:</label>  
    <div class="col-sm-4">  
        <input type="text" name="eid" id="id_eid" required maxlength="20" value="{{ employee.eid }}"/>  
    </div>  
  </div>  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Employee Name:</label>  
    <div class="col-sm-4">  
        <input type="text" name="ename" id="id_ename" required maxlength="100" value="{{ employee.ename }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Employee Email:</label>  
    <div class="col-sm-4">  
        <input type="email" name="eemail" id="id_eemail" required maxlength="254" value="{{ employee.eemail }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Employee Contact:</label>  
    <div class="col-sm-4">  
        <input type="text" name="econtact" id="id_econtact" required maxlength="15" value="{{ employee.econtact }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <button type="submit" class="btn btn-success">Update</button>  
    </div>  
  </div>  
    </div>  
</form>  
</body>  
</html>  

LsManagement/employee/templates/index.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Index</title>  
    {% load staticfiles %}  
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/> 
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script> 
</head>  
<body>  
<form method="POST" class="post-form" action="/emp">  
        {% csrf_token %}  
    <div class="container">  
<br>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <h3>Enter Details</h3>  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Employee Id:</label>  
    <div class="col-sm-4">  
      {{ form.eid }}  
    </div>  
  </div>  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Employee Name:</label>  
    <div class="col-sm-4">  
      {{ form.ename }}  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Employee Email:</label>  
    <div class="col-sm-4">  
      {{ form.eemail }}  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Employee Contact:</label>  
    <div class="col-sm-4">  
      {{ form.econtact }}  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <button type="submit" class="btn btn-primary">Submit</button>  
    </div>  
  </div>  
    </div>  
</form>  
</body>  
</html> 

LsManagement/employee/templates/show.html
<!DOCTYPE html>  
<html lang="en">  
<head>
    <meta charset="UTF-8">  
    <title>Employee Records</title>  
     {% load staticfiles %}  
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>  
<body>  
<table class="table table-striped table-bordered table-sm">  
    <thead class="thead-dark">  
    <tr>  
        <th>Employee ID</th>  
        <th>Employee Name</th>  
        <th>Employee Email</th>  
        <th>Employee Contact</th>  
        <th>Actions</th>  
    </tr>  
    </thead>  
    <tbody>  
{% for employee in employees %}  
    <tr>  
        <td>{{ employee.eid }}</td>  
        <td>{{ employee.ename }}</td>  
        <td>{{ employee.eemail }}</td>  
        <td>{{ employee.econtact }}</td>  
        <td>  
            <a href="/edit/{{ employee.id }}"><span class="glyphicon glyphicon-pencil" >Edit</span></a>  
            <a href="/delete/{{ employee.id }}">Delete</a>  
        </td>  
    </tr>  
{% endfor %}  
    </tbody>  
</table>  
<br>  
<br>  
<center><a href="/emp" class="btn btn-primary">Add New Record</a></center>  
</body>  
</html>  

LsManagement/music/templates/login/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Login V13</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->	
	<link rel="icon" type="image/png" href="{% static '/login/images/icons/favicon.ico' %}" />
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css"  href="{% static 'login/vendor/bootstrap/css/bootstrap.min.css' %}" href="">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'login/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'login/fonts/Linearicons-Free-v1.0.0/icon-font.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'login/fonts/iconic/css/material-design-iconic-font.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'login/vendor/animate/animate.css' %}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{% static 'login/vendor/css-hamburgers/hamburgers.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'login/vendor/animsition/css/animsition.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'login/vendor/select2/select2.min.css' %}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{% static 'login/vendor/daterangepicker/daterangepicker.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'login/css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'login/css/main.css' %}">
<!--===============================================================================================-->
</head>
<body style="background-color: #999999;">
	
	<div class="limiter">
		<div class="container-login100">
			<div class="login100-more" style="background-image: url({% static 'login/images/bg-01.jpg' %});"></div>

			<div class="wrap-login100 p-l-50 p-r-50 p-t-72 p-b-50">
				<form class="login100-form validate-form" action="/music/registerUsers/" method="post">
				{% csrf_token %}
					<span class="login100-form-title p-b-59">
						Sign Up
					</span>

					<div class="wrap-input100 validate-input" data-validate="Name is required">
						<span class="label-input100">Full Name</span>
						<input class="input100" type="text" name="userName" placeholder="Name...">
						<span class="focus-input100"></span>
					</div>

					<div class="wrap-input100 validate-input" data-validate="Name is required">
						<span class="label-input100">Mobile</span>
						<input class="input100" type="text" name="mobile" placeholder="Name...">
						<span class="focus-input100"></span>
					</div>

					<div class="wrap-input100 validate-input" data-validate = "Valid email is required: ex@abc.xyz">
						<span class="label-input100">Email</span>
						<input class="input100" type="text" name="email" placeholder="Email addess...">
						<span class="focus-input100"></span>
					</div>

					<div class="wrap-input100 validate-input" data-validate="city is required">
						<span class="label-input100">city</span>
						<input class="input100" type="text" name="city" placeholder="city...">
						<span class="focus-input100"></span>
					</div>

					<div class="wrap-input100 validate-input" data-validate="city is required">
						<span class="label-input100">State</span>
						<input class="input100" type="text" name="state" placeholder="state...">
						<span class="focus-input100"></span>
					</div>

					<div class="wrap-input100 validate-input" data-validate="addess is required">
						<span class="label-input100">Address</span>
						<input class="input100" type="text" name="address" placeholder="address...">
						<span class="focus-input100"></span>
					</div>

					

					<div class="wrap-input100 validate-input" data-validate = "Password is required">
						<span class="label-input100">Password</span>
						<input class="input100" type="text" name="password" placeholder="*************">
						<span class="focus-input100"></span>
					</div>

					<div class="wrap-input100 validate-input" data-validate = "Repeat Password is required">
						<span class="label-input100">Repeat Password</span>
						<input class="input100" type="text" name="repeat-pass" placeholder="*************">
						<span class="focus-input100"></span>
					</div>

					<div class="flex-m w-full p-b-33">
						<div class="contact100-form-checkbox">
							<input class="input-checkbox100" id="ckb1" type="checkbox" name="remember-me">
							<label class="label-checkbox100" for="ckb1">
								<span class="txt1">
									I agree to the
									<a href="#" class="txt2 hov1">
										Terms of User
									</a>
								</span>
							</label>
						</div>

						
					</div>

					<div class="container-login100-form-btn">
						<div class="wrap-login100-form-btn">
							<div class="login100-form-bgbtn"></div>
							<button class="login100-form-btn">
								Sign Up
							</button>
						</div>

						<a href="/login/registerUsers" class="dis-block txt3 hov1 p-r-30 p-t-10 p-b-10 p-l-30">
							Sign in
							<i class="fa fa-long-arrow-right m-l-5"></i>
						</a>
					</div>
				</form>
			</div>
		</div>
	</div>
	
<!--===============================================================================================-->
	<script src="{% static 'login/vendor/jquery/jquery-3.2.1.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'login/vendor/animsition/js/animsition.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'login/vendor/bootstrap/js/popper.js' %}"></script>
	<script src="{% static 'login/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'login/vendor/select2/select2.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'login/vendor/daterangepicker/moment.min.js' %}"></script>
	<script src="{% static 'login/vendor/daterangepicker/daterangepicker.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'login/vendor/countdowntime/countdowntime.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'login/js/main.js' %}"></script>

</body>
</html>

LsManagement/music/templates/login/signIn.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Login V3</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->	
	<link rel="icon" type="image/png" href="{% static '/login/images/icons/favicon.ico' %}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static '/login/vendor/bootstrap/css/bootstrap.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static '/login/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static '/login/fonts/iconic/css/material-design-iconic-font.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static '/login/vendor/animate/animate.css' %}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{% static '/login/vendor/css-hamburgers/hamburgers.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static '/login/vendor/animsition/css/animsition.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static '/login/vendor/select2/select2.min.css' %}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{% static '/login/vendor/daterangepicker/daterangepicker.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static '/login/css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static '/login/css/main.css' %}">
<!--===============================================================================================-->
</head>
<body>
	
	<div class="limiter">
		<div class="container-login100" style="background-image: url({% static '/login/images/bg-001.jpg' %});">
			<div class="wrap-login100">
			{{context.text}}
				<form class="login100-form validate-form">
					<span class="login100-form-logo">
						<i class="zmdi zmdi-landscape"></i>
					</span>

					<span class="login100-form-title p-b-34 p-t-27">
						Log in
					</span>

					<div class="wrap-input100 validate-input" data-validate = "Enter username">
						<input class="input100" type="text" name="username" placeholder="Username">
						<span class="focus-input100" data-placeholder="&#xf207;"></span>
					</div>

					<div class="wrap-input100 validate-input" data-validate="Enter password">
						<input class="input100" type="password" name="pass" placeholder="Password">
						<span class="focus-input100" data-placeholder="&#xf191;"></span>
					</div>

					<div class="contact100-form-checkbox">
						<input class="input-checkbox100" id="ckb1" type="checkbox" name="remember-me">
						<label class="label-checkbox100" for="ckb1">
							Remember me
						</label>
					</div>

					<div class="container-login100-form-btn">
						<button class="login100-form-btn">
							Login
						</button>
					</div>

					<div class="text-center p-t-90">
						<a class="txt1" href="#">
							Forgot Password?
						</a>
					</div>
				</form>
			</div>
		</div>
	</div>
	

	<div id="dropDownSelect1"></div>
	
<!--===============================================================================================-->
	<script src="{% static '/login/vendor/jquery/jquery-3.2.1.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static '/login/vendor/animsition/js/animsition.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static '/login/vendor/bootstrap/js/popper.js' %}"></script>
	<script src="{% static '/login/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static '/login/vendor/select2/select2.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static '/login/vendor/daterangepicker/moment.min.js' %}"></script>
	<script src="{% static '/login/vendor/daterangepicker/daterangepicker.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static '/login/vendor/countdowntime/countdowntime.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static '/login/js/main.js' %}"></script>

</body>
</html>

LsManagement/music/templates/music/addAlbum.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container">
  <h2>Horizontal form</h2>
  <form class="form-horizontal" action="/music/addMusicAlbum/" method="post">
  {% csrf_token %}
    <div class="form-group">
      <label class="control-label col-sm-2" for="email">Artist Name:</label>
      <div class="col-sm-10">
        <input type="text" class="form-control" id="artist" placeholder="Enter Artist Name" name="artist" value="{{request.form.artist}}">
      </div>
    </div>

    <div class="form-group">
      <label class="control-label col-sm-2" for="pwd">Album Title:</label>
      <div class="col-sm-10">          
        <input type="text" class="form-control" id="title" placeholder="Enter album title" name="title">
      </div>
    </div>

    <div class="form-group">
      <label class="control-label col-sm-2" for="pwd">Album Genre:</label>
      <div class="col-sm-10">          
        <input type="text" class="form-control" id="genre" placeholder="Enter album genre" name="genre">
      </div>
    </div>

    <div class="form-group">
      <label class="control-label col-sm-2" for="logo">Album Logo:</label>
      <div class="col-sm-10">          
        <input type="text" class="form-control" id="logo" placeholder="Enter album logo" name="logo">
      </div>
    </div>
    
    <div class="form-group">        
      <div class="col-sm-offset-2 col-sm-10">
        <button type="submit" class="btn btn-default">Submit</button>
      </div>
    </div>
  </form>
</div>

</body>
</html>

LsManagement/music/templates/music/detail.html
<!DOCTYPE html>
<html>
<head>
	<title>Music World</title>
</head>
<body>
<div class="container">
<div style="width: 978px; margin: 0 auto;">
	<div class="header" style="width: 978px; height:100px; background-color: #e2e2e2; text-align: center; ">
		<div style="width:300px; float: left; color: green; padding: 10px;">
			{{album.artist}}
		</div>
		<div style="margin: 10px auto; padding: 20px;float: left;">
			<form>
				<input style="width: 409px; height: 35px;" type="text" name="searchSongs" id="searchSongs">
				<button style="padding: 11px;" >Search</button>
			</form>
		</div>
		<div style="clear: both;" ></div>
	</div>
	<div class="left" style="width: 250px; height:600px; float: left;">
		<div style="display: inline-block;">
		{% for types in all_types %}  
			<div style="margin-top: 10px;padding: 2px;">		{{types.song_type}}
			</div>
		{% endfor %}
		</div>
	</div>
	<div class="body" style="width: 728px;height:600px;background-color: green;float: left;"><audio controls="controls">
  <source src="https://youtu.be/TRa9IMvccjg?t=16" type="audio/mpeg">
</audio></div>
	<div style="clear: both;"></div>
	<div class="footer" style="width: 978px; text-align: center; height: 100px; padding: 10px;">
		Powered by musicworld.com @2017-2018
	</div>
</div>
	
</div>

</body>
</html>

LsManagement/music/templates/music/index.html
{% extends 'music/base.html' %}
{% block body %}

{%for album in all_albums %}
<div class="container" >
  <div style="width: 50%; float: left;">
    {{album.recordId}}
  </div>
</div>

{%endfor%}

{% endblock %}